services:
  postgres:
    image: postgres:17.6-alpine3.22
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: assistant
    ports: ["5432:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:8.2-alpine3.22
    ports: ["6379:6379"]
  # Optional: app services
  api:
    build:
      context: .
      dockerfile: ./packages/api/Dockerfile
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - API_PORT=${API_PORT}
    ports: ["${API_PORT:-3001}:3001"]
    depends_on: [postgres, redis]
  ui:
    build:
      context: .
      dockerfile: ./packages/ui/Dockerfile
    environment:
      - UI_PORT=${UI_PORT}
    ports: ["${UI_PORT:-5173}:5173"]
    depends_on: [api]
  ai:
    build:
      context: .
      dockerfile: ./packages/ai/Dockerfile
    environment:
      - AI_PORT=${AI_PORT}
    ports: ["${AI_PORT:-8000}:8000"]
  workers:
    build:
      context: .
      dockerfile: ./packages/workers/Dockerfile
    environment:
      - REDIS_URL=${REDIS_URL}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - GITHUB_OWNER=${GITHUB_OWNER}
      - GITHUB_REPO=${GITHUB_REPO}
    depends_on: [redis, api]
  scheduler:
    build:
      context: .
      dockerfile: ./packages/scheduler/Dockerfile
    environment:
      - REDIS_URL=${REDIS_URL}
    depends_on: [redis]
    ports: ["3002:3002"]

volumes:
  pgdata:
