services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: assistant
    ports: ["5432:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:7
    ports: ["6379:6379"]
  # Optional: app services
  api:
    build: ./packages/api
    env_file: .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - API_PORT=${API_PORT}
    ports: ["${API_PORT:-3001}:3001"]
    depends_on: [postgres, redis]
  ui:
    build: ./packages/ui
    env_file: .env
    environment:
      - UI_PORT=${UI_PORT}
    ports: ["${UI_PORT:-5173}:5173"]
    depends_on: [api]
  ai:
    build: ./packages/ai
    env_file: .env
    environment:
      - AI_PORT=${AI_PORT}
    ports: ["${AI_PORT:-8000}:8000"]
  workers:
    build: ./packages/workers
    env_file: .env
    environment:
      - REDIS_URL=${REDIS_URL}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - GITHUB_OWNER=${GITHUB_OWNER}
      - GITHUB_REPO=${GITHUB_REPO}
    depends_on: [redis, api]
volumes:
  pgdata:
