name: CI

on:
  push:
    branches-ignore: [main]
  pull_request:
    branches: [main]

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      global: ${{ steps.filter.outputs.global }}
      api: ${{ steps.filter.outputs.api }}
      scheduler: ${{ steps.filter.outputs.scheduler }}
      workers: ${{ steps.filter.outputs.workers }}
      ui: ${{ steps.filter.outputs.ui }}
      ai: ${{ steps.filter.outputs.ai }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            global:
              - 'Makefile'
              - 'docker-compose.yml'
              - 'packages/config/**'
              - 'packages/schemas/**'
              - '.github/workflows/ci.yml'
            api:
              - 'packages/api/**'
              - 'packages/schemas/**'
            scheduler:
              - 'packages/scheduler/**'
            workers:
              - 'packages/workers/**'
            ui:
              - 'packages/ui/**'
            ai:
              - 'packages/ai/**'
  # Build API Docker image
  build-api:
    runs-on: ubuntu-latest
    needs: [changes]
    if: needs.changes.outputs.api == 'true' || needs.changes.outputs.global == 'true'
    steps:
      - uses: actions/checkout@v4
      - name: Setup Docker
        uses: docker/setup-buildx-action@v3
      - name: Build API image
        run: make build.api
      - name: Save API image as artifact
        run: make save.api
      - name: Upload API image artifact
        uses: actions/upload-artifact@v4
        with:
          name: api-image
          path: api-image.tar

  # Build Scheduler Docker image
  build-scheduler:
    runs-on: ubuntu-latest
    needs: [changes]
    if: needs.changes.outputs.scheduler == 'true' || needs.changes.outputs.global == 'true'
    steps:
      - uses: actions/checkout@v4
      - name: Setup Docker
        uses: docker/setup-buildx-action@v3
      - name: Build Scheduler image
        run: make build.scheduler
      - name: Save Scheduler image as artifact
        run: make save.scheduler
      - name: Upload Scheduler image artifact
        uses: actions/upload-artifact@v4
        with:
          name: scheduler-image
          path: scheduler-image.tar

  # Tests unitaires (conditionnels selon les fichiers modifiés)
  test-api-unit:
    runs-on: ubuntu-latest
    needs: [changes]
    if: needs.changes.outputs.api == 'true' || needs.changes.outputs.global == 'true'
    steps:
      - uses: actions/checkout@v4
      - name: Setup Docker
        uses: docker/setup-buildx-action@v3
      - name: Start services
        run: make up
      - name: Test API Unit
        run: make test.unit.api

  test-scheduler-unit:
    runs-on: ubuntu-latest
    needs: [changes, build-scheduler]
    if: needs.changes.outputs.scheduler == 'true' || needs.changes.outputs.global == 'true'
    steps:
      - uses: actions/checkout@v4
      - name: Setup Docker
        uses: docker/setup-buildx-action@v3
      - name: Start services
        run: make up
      - name: Test Scheduler Unit
        run: make test.unit.scheduler

  test-workers-unit:
    runs-on: ubuntu-latest
    needs: [changes]
    if: needs.changes.outputs.workers == 'true' || needs.changes.outputs.global == 'true'
    steps:
      - uses: actions/checkout@v4
      - name: Setup Docker
        uses: docker/setup-buildx-action@v3
      - name: Start services
        run: make up
      - name: Test Workers Unit
        run: make test.unit.workers

  test-ui-unit:
    runs-on: ubuntu-latest
    needs: [changes]
    if: needs.changes.outputs.ui == 'true' || needs.changes.outputs.global == 'true'
    steps:
      - uses: actions/checkout@v4
      - name: Setup Docker
        uses: docker/setup-buildx-action@v3
      - name: Start services
        run: make up
      - name: Test UI Unit
        run: make test.unit.ui

  test-ai-unit:
    runs-on: ubuntu-latest
    needs: [changes]
    if: needs.changes.outputs.ai == 'true' || needs.changes.outputs.global == 'true'
    steps:
      - uses: actions/checkout@v4
      - name: Setup Docker
        uses: docker/setup-buildx-action@v3
      - name: Start services
        run: make up
      - name: Test AI Unit
        run: make test.unit.ai

  # Tests d'intégration P2P (dépendent des tests unitaires)
  test-scheduler-api:
    runs-on: ubuntu-latest
    needs: [changes, test-scheduler-unit, test-api-unit]
    if: needs.changes.outputs.scheduler == 'true' || needs.changes.outputs.api == 'true' || needs.changes.outputs.global == 'true'
    steps:
      - uses: actions/checkout@v4
      - name: Setup Docker
        uses: docker/setup-buildx-action@v3
      - name: Start services
        run: make up
      - name: Test Scheduler-API Integration
        run: make test.integration.scheduler-api

  test-scheduler-workers:
    runs-on: ubuntu-latest
    needs: [changes, test-scheduler-unit, test-workers-unit, test-api-unit]
    if: needs.changes.outputs.scheduler == 'true' || needs.changes.outputs.workers == 'true' || needs.changes.outputs.api == 'true' || needs.changes.outputs.global == 'true'
    steps:
      - uses: actions/checkout@v4
      - name: Setup Docker
        uses: docker/setup-buildx-action@v3
      - name: Start services
        run: make up
      - name: Test Scheduler-Workers Integration
        run: make test.integration.scheduler-workers-api

  test-workers-api:
    runs-on: ubuntu-latest
    needs: [changes, test-workers-unit, test-api-unit]
    if: needs.changes.outputs.workers == 'true' || needs.changes.outputs.api == 'true' || needs.changes.outputs.global == 'true'
    steps:
      - uses: actions/checkout@v4
      - name: Setup Docker
        uses: docker/setup-buildx-action@v3
      - name: Start services
        run: make up
      - name: Test Workers-API Integration
        run: make test.integration.workers-api

  test-ui-api:
    runs-on: ubuntu-latest
    needs: [changes, test-ui-unit, test-api-unit]
    if: needs.changes.outputs.ui == 'true' || needs.changes.outputs.api == 'true' || needs.changes.outputs.global == 'true'
    steps:
      - uses: actions/checkout@v4
      - name: Setup Docker
        uses: docker/setup-buildx-action@v3
      - name: Start services
        run: make up
      - name: Test UI-API E2E
        run: make test.e2e.ui-api

  # Tests P2P avec AI
  test-scheduler-ai:
    runs-on: ubuntu-latest
    needs: [changes, test-scheduler-unit, test-ai-unit]
    if: needs.changes.outputs.scheduler == 'true' || needs.changes.outputs.ai == 'true' || needs.changes.outputs.global == 'true'
    steps:
      - uses: actions/checkout@v4
      - name: Setup Docker
        uses: docker/setup-buildx-action@v3
      - name: Start services
        run: make up
      - name: Test Scheduler-AI Integration
        run: make test.integration.scheduler-ai

  test-workers-ai:
    runs-on: ubuntu-latest
    needs: [changes, test-workers-unit, test-ai-unit]
    if: needs.changes.outputs.workers == 'true' || needs.changes.outputs.ai == 'true' || needs.changes.outputs.global == 'true'
    steps:
      - uses: actions/checkout@v4
      - name: Setup Docker
        uses: docker/setup-buildx-action@v3
      - name: Start services
        run: make up
      - name: Test Workers-AI Integration
        run: make test.integration.workers-ai
