name: CI

on:
  pull_request:
    branches: [main]

jobs:
  # Tests unitaires (conditionnels selon les fichiers modifiés)
  test-api-unit:
    runs-on: ubuntu-latest
    if: github.event.pull_request.files && (contains(github.event.pull_request.files.*.name, 'packages/api/') || contains(github.event.pull_request.files.*.name, 'packages/schemas/') || contains(github.event.pull_request.files.*.name, 'Makefile') || contains(github.event.pull_request.files.*.name, 'docker-compose.yml') || contains(github.event.pull_request.files.*.name, 'packages/config/'))
    steps:
      - uses: actions/checkout@v4
      - name: Setup Docker
        uses: docker/setup-buildx-action@v3
      - name: Start services
        run: make up
      - name: Test API Unit
        run: make test.unit.api

  test-scheduler-unit:
    runs-on: ubuntu-latest
    if: github.event.pull_request.files && (contains(github.event.pull_request.files.*.name, 'packages/scheduler/') || contains(github.event.pull_request.files.*.name, 'Makefile') || contains(github.event.pull_request.files.*.name, 'docker-compose.yml') || contains(github.event.pull_request.files.*.name, 'packages/config/'))
    steps:
      - uses: actions/checkout@v4
      - name: Setup Docker
        uses: docker/setup-buildx-action@v3
      - name: Start services
        run: make up
      - name: Test Scheduler Unit
        run: make test.unit.scheduler

  test-workers-unit:
    runs-on: ubuntu-latest
    if: github.event.pull_request.files && (contains(github.event.pull_request.files.*.name, 'packages/workers/') || contains(github.event.pull_request.files.*.name, 'Makefile') || contains(github.event.pull_request.files.*.name, 'docker-compose.yml') || contains(github.event.pull_request.files.*.name, 'packages/config/'))
    steps:
      - uses: actions/checkout@v4
      - name: Setup Docker
        uses: docker/setup-buildx-action@v3
      - name: Start services
        run: make up
      - name: Test Workers Unit
        run: make test.unit.workers

  test-ui-unit:
    runs-on: ubuntu-latest
    if: github.event.pull_request.files && (contains(github.event.pull_request.files.*.name, 'packages/ui/') || contains(github.event.pull_request.files.*.name, 'Makefile') || contains(github.event.pull_request.files.*.name, 'docker-compose.yml') || contains(github.event.pull_request.files.*.name, 'packages/config/'))
    steps:
      - uses: actions/checkout@v4
      - name: Setup Docker
        uses: docker/setup-buildx-action@v3
      - name: Start services
        run: make up
      - name: Test UI Unit
        run: make test.unit.ui

  test-ai-unit:
    runs-on: ubuntu-latest
    if: github.event.pull_request.files && (contains(github.event.pull_request.files.*.name, 'packages/ai/') || contains(github.event.pull_request.files.*.name, 'Makefile') || contains(github.event.pull_request.files.*.name, 'docker-compose.yml') || contains(github.event.pull_request.files.*.name, 'packages/config/'))
    steps:
      - uses: actions/checkout@v4
      - name: Setup Docker
        uses: docker/setup-buildx-action@v3
      - name: Start services
        run: make up
      - name: Test AI Unit
        run: make test.unit.ai

  # Tests d'intégration P2P (dépendent des tests unitaires)
  test-scheduler-api:
    runs-on: ubuntu-latest
    if: github.event.pull_request.files && (contains(github.event.pull_request.files.*.name, 'packages/scheduler/') || contains(github.event.pull_request.files.*.name, 'packages/api/') || contains(github.event.pull_request.files.*.name, 'packages/schemas/') || contains(github.event.pull_request.files.*.name, 'Makefile') || contains(github.event.pull_request.files.*.name, 'docker-compose.yml') || contains(github.event.pull_request.files.*.name, 'packages/config/'))
    needs: [test-scheduler-unit, test-api-unit]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Docker
        uses: docker/setup-buildx-action@v3
      - name: Start services
        run: make up
      - name: Test Scheduler-API Integration
        run: make test.integration.scheduler-api

  test-scheduler-workers:
    runs-on: ubuntu-latest
    if: github.event.pull_request.files && (contains(github.event.pull_request.files.*.name, 'packages/scheduler/') || contains(github.event.pull_request.files.*.name, 'packages/workers/') || contains(github.event.pull_request.files.*.name, 'packages/api/') || contains(github.event.pull_request.files.*.name, 'packages/schemas/') || contains(github.event.pull_request.files.*.name, 'Makefile') || contains(github.event.pull_request.files.*.name, 'docker-compose.yml') || contains(github.event.pull_request.files.*.name, 'packages/config/'))
    needs: [test-scheduler-unit, test-workers-unit, test-api-unit]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Docker
        uses: docker/setup-buildx-action@v3
      - name: Start services
        run: make up
      - name: Test Scheduler-Workers Integration
        run: make test.integration.scheduler-workers-api

  test-workers-api:
    runs-on: ubuntu-latest
    if: github.event.pull_request.files && (contains(github.event.pull_request.files.*.name, 'packages/workers/') || contains(github.event.pull_request.files.*.name, 'packages/api/') || contains(github.event.pull_request.files.*.name, 'packages/schemas/') || contains(github.event.pull_request.files.*.name, 'Makefile') || contains(github.event.pull_request.files.*.name, 'docker-compose.yml') || contains(github.event.pull_request.files.*.name, 'packages/config/'))
    needs: [test-workers-unit, test-api-unit, test-scheduler-workers]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Docker
        uses: docker/setup-buildx-action@v3
      - name: Start services
        run: make up
      - name: Test Workers-API Integration
        run: make test.integration.workers-api

  test-ui-api:
    runs-on: ubuntu-latest
    if: github.event.pull_request.files && (contains(github.event.pull_request.files.*.name, 'packages/ui/') || contains(github.event.pull_request.files.*.name, 'packages/api/') || contains(github.event.pull_request.files.*.name, 'packages/schemas/') || contains(github.event.pull_request.files.*.name, 'Makefile') || contains(github.event.pull_request.files.*.name, 'docker-compose.yml') || contains(github.event.pull_request.files.*.name, 'packages/config/'))
    needs: [test-ui-unit, test-api-unit]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Docker
        uses: docker/setup-buildx-action@v3
      - name: Start services
        run: make up
      - name: Test UI-API E2E
        run: make test.e2e.ui-api

  # Tests P2P avec AI
  test-scheduler-ai:
    runs-on: ubuntu-latest
    if: github.event.pull_request.files && (contains(github.event.pull_request.files.*.name, 'packages/scheduler/') || contains(github.event.pull_request.files.*.name, 'packages/ai/') || contains(github.event.pull_request.files.*.name, 'Makefile') || contains(github.event.pull_request.files.*.name, 'docker-compose.yml') || contains(github.event.pull_request.files.*.name, 'packages/config/'))
    needs: [test-scheduler-unit, test-ai-unit]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Docker
        uses: docker/setup-buildx-action@v3
      - name: Start services
        run: make up
      - name: Test Scheduler-AI Integration
        run: make test.integration.scheduler-ai

  test-workers-ai:
    runs-on: ubuntu-latest
    if: github.event.pull_request.files && (contains(github.event.pull_request.files.*.name, 'packages/workers/') || contains(github.event.pull_request.files.*.name, 'packages/ai/') || contains(github.event.pull_request.files.*.name, 'Makefile') || contains(github.event.pull_request.files.*.name, 'docker-compose.yml') || contains(github.event.pull_request.files.*.name, 'packages/config/'))
    needs: [test-workers-unit, test-ai-unit]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Docker
        uses: docker/setup-buildx-action@v3
      - name: Start services
        run: make up
      - name: Test Workers-AI Integration
        run: make test.integration.workers-ai
